version: "2.1"

services:

  # The Cookie on Demand service, a J2E system
  tcf_system:
    image: dd-j2e
    container_name: dd_system
    environment:
      - bank_host=dd_partners
      - bank_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - external_partners

  # The external partners, implemented as .Net services
  external_partners:
    image: dd-dotnet
    container_name: dd_partners
    expose:
      - "9090"
    ports:
      - "9090:9090"

  # A simple java CLI
  client:
    image: dd-j2e
    container_name: dd_client
    command: "dd_system 8080"
    volumes:
      - .:/host
    depends_on:
      tcf_system:
        condition: service_healthy
    stdin_open: true
    tty: true