package stubs.delivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-20T08:11:15.104+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://localhost:8080", name = "DeliverySystemWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeliverySystemWebService {

    @WebMethod
    @RequestWrapper(localName = "getParcel", targetNamespace = "http://localhost:8080", className = "stubs.delivery.GetParcel")
    @ResponseWrapper(localName = "getParcelResponse", targetNamespace = "http://localhost:8080", className = "stubs.delivery.GetParcelResponse")
    @WebResult(name = "parcel", targetNamespace = "")
    public stubs.delivery.Parcel getParcel(
        @WebParam(name = "parcelReference", targetNamespace = "")
        java.lang.String parcelReference
    );

    @WebMethod
    @RequestWrapper(localName = "initDatabase", targetNamespace = "http://localhost:8080", className = "stubs.delivery.InitDatabase")
    @ResponseWrapper(localName = "initDatabaseResponse", targetNamespace = "http://localhost:8080", className = "stubs.delivery.InitDatabaseResponse")
    public void initDatabase();
}
