package stubs.billing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-28T16:45:47.947+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "BillServiceImplService", 
                  wsdlLocation = "file:/home/maeldelaby/Cours/2020/ISA_DEVOPS/projet-isa-devops-20-team-j-20/front/src/main/resources/BillServiceImpl.wsdl",
                  targetNamespace = "http://localhost:8080/bill") 
public class BillServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/bill", "BillServiceImplService");
    public final static QName BillServiceImplPort = new QName("http://localhost:8080/bill", "BillServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/maeldelaby/Cours/2020/ISA_DEVOPS/projet-isa-devops-20-team-j-20/front/src/main/resources/BillServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/maeldelaby/Cours/2020/ISA_DEVOPS/projet-isa-devops-20-team-j-20/front/src/main/resources/BillServiceImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillServiceImplPort")
    public BillService getBillServiceImplPort() {
        return super.getPort(BillServiceImplPort, BillService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillServiceImplPort")
    public BillService getBillServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BillServiceImplPort, BillService.class, features);
    }

}
