package stubs.billing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-25T18:08:35.918+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://localhost:8080/bill", name = "BillService")
@XmlSeeAlso({ObjectFactory.class})
public interface BillService {

    @WebMethod
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://localhost:8080/bill", className = "stubs.billing.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://localhost:8080/bill", className = "stubs.billing.SendBillResponse")
    @WebResult(name = "cart_contents", targetNamespace = "")
    public java.lang.String sendBill(
        @WebParam(name = "bill_amount", targetNamespace = "")
        java.lang.String billAmount
    ) throws Exception_Exception;
}
