
package stubs.billing;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-20T08:45:05.557+01:00
 * Generated source version: 2.7.9
 */

@WebFault(name = "Exception", targetNamespace = "http://localhost:8080/bill")
public class Exception_Exception extends java.lang.Exception {
    
    private stubs.billing.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, stubs.billing.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, stubs.billing.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public stubs.billing.Exception getFaultInfo() {
        return this.exception;
    }
}
