package stubs.plannings;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-03-19T19:51:00.010+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "PlanningWebServiceImplService", 
                  wsdlLocation = "file:/home/florian/Documents/Isa-devops/projet-isa-devops-20-team-j-20/front/src/main/resources/PlanningWebServiceImpl.wsdl",
                  targetNamespace = "http://localhost:8080") 
public class PlanningWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080", "PlanningWebServiceImplService");
    public final static QName PlanningWebServiceImplPort = new QName("http://localhost:8080", "PlanningWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/florian/Documents/Isa-devops/projet-isa-devops-20-team-j-20/front/src/main/resources/PlanningWebServiceImpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlanningWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/florian/Documents/Isa-devops/projet-isa-devops-20-team-j-20/front/src/main/resources/PlanningWebServiceImpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlanningWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlanningWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanningWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PlanningWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PlanningWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PlanningWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PlanningWebService
     */
    @WebEndpoint(name = "PlanningWebServiceImplPort")
    public PlanningWebService getPlanningWebServiceImplPort() {
        return super.getPort(PlanningWebServiceImplPort, PlanningWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlanningWebService
     */
    @WebEndpoint(name = "PlanningWebServiceImplPort")
    public PlanningWebService getPlanningWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PlanningWebServiceImplPort, PlanningWebService.class, features);
    }

}
